version: '3.4'
services:
  stan_model_container:
    image: jrnold/rstan
    command: Rscript /app/main.R
    working_dir: /app
    volumes:
      - ./my_model.stan:/app/my_model.stan
      - ./main.R:/app/main.R
      - ./fit.rda:/app/fit.rda

